project:
  type: website

website:
  title: 'Code Snippet Chronicles'
  navbar:
    right:
      - icon: github
        href: https://github.com/geeknees/quarto
      - icon: twitter
        href: https://twitter.com/_geeknees
      - icon: rss
        href: index.xml
google-analytics: 'G-JWH4HML8WX'
format:
  html:
    theme: sandstone
    css: styles.css
