project:
  type: website

website:
  title: "quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/geeknees
      - icon: twitter
        href: https://twitter.com/_geeknees
format:
  html:
    theme: cosmo
    css: styles.css
