# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'activesupport'
gem 'boxcars'
gem 'charty'
gem 'cosine-similarity'
gem 'daru'
gem 'daru-view', github: 'SciRuby/daru-view'
gem 'eth', github: 'q9f/eth.rb'
gem 'gruff'
gem 'iruby'
gem 'langchainrb'
gem 'matrix'
gem 'numo-narray'
gem 'nyaplot', github: 'SciRuby/nyaplot'
gem 'pg'
gem 'rb_prob', github: 'geeknees/rb_prob'
gem 'red-datasets'
gem 'rubocop'
gem 'ruby-openai'
